-- ============================================================
-- Fit Match · Chat privado 1-a-1 (mensajes directos)
-- Tabla de mensajes entre dos usuarios + seguridad (RLS) + realtime.
-- COMO USAR: Supabase -> SQL Editor -> pega TODO -> Run.
-- ============================================================

-- 1) Tabla
CREATE TABLE IF NOT EXISTS public.direct_messages (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id   uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  receiver_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  text        text NOT NULL,
  read        boolean NOT NULL DEFAULT false,
  created_at  timestamptz NOT NULL DEFAULT now()
);

-- Indice para traer rapido una conversacion
CREATE INDEX IF NOT EXISTS idx_dm_pair ON public.direct_messages (sender_id, receiver_id, id);

-- 2) Seguridad (RLS): cada quien solo ve/usa SUS conversaciones
ALTER TABLE public.direct_messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS dm_select ON public.direct_messages;
CREATE POLICY dm_select ON public.direct_messages
  FOR SELECT USING (auth.uid() = sender_id OR auth.uid() = receiver_id);

DROP POLICY IF EXISTS dm_insert ON public.direct_messages;
CREATE POLICY dm_insert ON public.direct_messages
  FOR INSERT WITH CHECK (auth.uid() = sender_id);

-- El receptor puede marcar como leido
DROP POLICY IF EXISTS dm_update ON public.direct_messages;
CREATE POLICY dm_update ON public.direct_messages
  FOR UPDATE USING (auth.uid() = receiver_id);

-- 3) Realtime (para que el mensaje llegue al instante)
ALTER PUBLICATION supabase_realtime ADD TABLE direct_messages;
